version: 0.2

env:
  variables:
    STAGE:  stg

phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.8
    commands:
    - npm install -g serverless@1.51.0
  build:
    commands:
    - (cd infra && serverless deploy -v --force --env=${STAGE})
    - (cd api && npm install && serverless deploy -v --force --env=${STAGE})